[package]
name = "discord"
version = "0.1.0"
edition = "2021"

[dependencies]
notify-rust = "4.8.0"
wry = "0.27.3"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.1"
embed_plist = "1.2.2"
objc = "0.2.7"
